name: Check PR

on:
  - pull_request

jobs:
  validate_code:
    name: Validate Code
    uses: ./.github/workflows/validate_code.yml
  test_bun_versions:
    name: Test Bun Versions and OS
    uses: ./.github/workflows/test_bun_versions.yml
