# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json

name: Check PR

on:
  - pull_request

jobs:
  # !UNDO BEFORE MERGE
  # validate_code:
  #   name: Validate Code
  #   uses: ./.github/workflows/validate_code.yml
  # test_bun_versions:
  #   name: Test Bun Versions
  #   uses: ./.github/workflows/test_bun_versions.yml
  test_windows:
    name: Test on Windows
    uses: ./.github/workflows/test_windows.yml
