name: Test on Windows

on:
  workflow_dispatch:
  workflow_call:

jobs:
  version:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        bun_version: ["1.2.23"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Bun ${{ matrix.bun_version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun_version }}

      - name: Install Dependencies
        id: install-deps
        shell: pwsh
        run: |
          bun install --frozen-lockfile

      - name: Run Tests
        shell: pwsh
        run: |
          bun bw test cliLog
        env:
          # ! REMOVE ME
          CI: false

      # ! UNCOMMENT BEFORE MERGE
      # - name: Run Tests Against Build
      #   shell: pwsh
      #   run: |
      #     bun bw build:test
