name: Test on Windows

on:
  workflow_dispatch:
  workflow_call:

jobs:
  version:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        bun_version: ["1.2.23"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Bun ${{ matrix.bun_version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun_version }}

      - name: Bun Cache
        id: bun-cache
        uses: actions/cache@v3
        with:
          path: ~/.bun
          key: node-modules-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            node-modules-

      - name: Install Dependencies
        shell: pwsh
        run: |
          bun --version
          bun install

      - name: Run Tests
        shell: pwsh
        run: |
          bun bw test runScriptInternals
        env:
          CI: false

      - name: Run Tests Against Build
        shell: pwsh
        run: |
          bun bw build:test
