name: Test on Windows

on:
  workflow_dispatch:
  workflow_call:

jobs:
  version:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        bun_version: ["1.2.23"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Bun ${{ matrix.bun_version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun_version }}

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }} Bun Cache
        id: bun-cache

      - name: Install Dependencies
        shell: pwsh
        run: |
          bun --version
          bun install

      - name: Run Tests
        shell: pwsh
        run: |
          bun bw test runScriptInternals
        env:
          # ! REMOVE ME
          CI: false

      # ! UNCOMMENT BEFORE MERGE
      # - name: Run Tests Against Build
      #   shell: pwsh
      #   run: |
      #     bun bw build:test
